name: AVD Hostpool Deployment
description: Deploy new VMs to a AVD Hostpool.
title: "[AVD Hostpool Deployment]"
#labels: ["deployment-request"]
body:
  - type: input
    id: creator
    attributes:
      label: "Your email address"
      description: "Please enter your email address so that we can tag the resources with you as the creator."
      placeholder: "email@ntnu.no"
    validations:
      required: true
  - type: dropdown
    id: Cluster
    attributes:
      label: Cluster
      description: Select the Azure Local Cluster
      options:
        - "Azlocal-C1"
        - "Azlocal-C2"
        - "Azloctest-C1"
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: Environment
      description: Select the which environment the deployment should run in
      options:
        - "Prod"
        - "Test"
    validations:
      required: true

  - type: dropdown
    id: Hostpool
    attributes:
      label: Hostpool
      description: Select which hostpool to deploy
      options:
        - "CAD"
        - "Employee"
        - "Demo"
        - "MathStat"
        - "Scientific"
    validations:
      required: true
