name: AVD Hostpool Deployment
description: Start a new AVD Hostpool deployment.
title: "[Hostpool Deployment]: ${{ github.event.inputs.Hostpool }}-${{ github.event.inputs.Environment }} "
labels: ["deployment-request"]
body:
  - type: dropdown
    id: Cluster
    attributes:
      label: Cluster
      description: Select the Azure Local Cluster
      options:
        - "Azlocal-c1"
        - "Azlocal-c2"
        - "Azloc-test-c1"
    validations:
      required: true
  - type: dropdown
    id: Environment
    attributes:
      label: Environment
      description: Select the which environment the deployment should run in
      options:
        - "prod"
        - "test"
    validations:
      required: true

  - type: dropdown
    id: Hostpool
    attributes:
      label: Hostpool
      description: Select which hostpool to deploy
      options:
        - "CAD"
        - "Employee"
        - "Demo"
        - "MathStat"
        - "Scientific"
    validations:
      required: true
